
- hosts: '{{ target }}'
  become: yes
  tasks:
  - name: Install lvm package
    yum:
      name: lvm2
      state: latest
  - name: Partitions Layout
    script: /data/git/terraform-openstack/scripts/iap_jboss_partition_layout.sh '{{ device }}'
